// TODO: ВО ВКЛАДКЕ ru ПЕРЕВЕСТИ ВСЕ С АНГЛИЙСКОГО НА РУССКИЙ
let translations = {
  'en': {
    'intro': 'IT is the most developing sphere in the world. Therefore, the search for qualified employees requires great effort. We bring a new understanding of the labour market. Emploreum is a bridge between IT companies and specialists.Emploreum is a decentralized labor exchange where all contracts between employee and employer are made through Ethereum blockchain. A professional experience, education, current level of knowledge in certain areas of IT is a cv-token of the employees which are used to evaluate and rank them. Employees have a rating which is an indicator of the quality of their work. At the same time, companies also have a rating reflecting the level of the company. With the quality of maintenance of companies and employees, the System is able to determine the cost per hour of employee\'s work.',
    'about': 'about',
    'team': 'team',
    'paper': 'paper',
    'technologies': 'technologies',
    'contact': 'contact',
    'short_descr': 'EDUCATION, EXPERIENCE, SKILLS - ONE TOKEN ON THE BLOCKCHAIN. THIS IS THE REVOLUTION IN RECRUITMENT OF IT EMPLOYEES.',
    'first_plus_n': 'A UNIQUE CV-TOKEN',
    'first_plus_d': 'Anyone can create his own labour book in the blockchain, which reflects the level of specific skills, experience, education, certificates.',
    'second_plus_n': 'ESCROW SMART CONTRACTS INSTEAD OF A LABOR CONTRACT',
    'second_plus_d': 'Jobs are a smart contract, with the requirement for work experience, and a level of certain skills.',
    'third_plus_n': 'COMPANIES PAY FOR SKILLS',
    'third_plus_d': 'Every skill (JS, C ++) costs different money on the labor market. Companies choose the developer level.',
    'four_plus_n': 'INTERNAL CURRENCY',
    'four_plus_d': 'Time. Companies pay per each hour of time worked on task using any skill or their combination(JS + Ruby on Rails).',
    'tm': 'TEAM MEMBERS',
    'rkh': 'Rinat Khatipov',
    'rkh_short': 'Founder, front-end developer, design, CEO',
    'rkh_long': 'Innopolis University student. Solidity developer, front-end developer, mobile app developer. Has experience in leading IT company in St. Petersburg. Is co-founder of many start-ups',
    'mik': 'Mickhail Magomedov',
    'mik_short': 'Founder, back-end developer, CEO',
    'mik_long': 'Student of Kazan Federal University. More than 5 years of work experience. Full stack web developer. Participated in the creation of 3 startups',
    'ilg': 'Ilgiz Zamaleev',
    'ilg_short': 'Founder, mobile-developer, UX, marketing',
    'ilg_long': 'Innopolis University student. ReactJS, React native, solidity developer. More than 3 years experience in web development.',
    'rig': 'Rinat Gumarov',
    'rig_short': 'Founder, back-end developer, big data',
    'rig_long': 'Innopolis University student. Solidity, Java, JavaScript developer. Have 3 years expirience in mobile development. Have expiriance in enterprice development.',
    'ay': 'Aydar Negimatzhanov',
    'ay_short': 'Founder, solidity developer, CEO',
    'ay_long': 'Innopolis University student. Solidity and Javascript developer. More than 1 year experience of developing Dapps using solidity. More than 5 blockchain projects.',
    'advisors': 'ADVISORS',
    'alg': 'Alexander Gryaznov',
    'alg_short': 'Chief Executive Officer',
    'alg_long': 'Cryptology Expert, programmer with more than 10 years experience. Alexander founded and conducts the first academic course on Ethereum at Innopolis University.',
    'w_paper': 'WHITE PAPER',
    'click_a_d': 'Click and Download',
    'paper_desc': 'this is what will help you understand',
    'tech_c': 'Technology cloud',
    'blockchain': 'BLOCK CHAIN',
    'blockchain_d': 'COMPLETELY DECENTRALIZED APPLICATION. IMMUTABLE RECORDS. YOUR CV-TOKEN CAN BE USED ANYWHERE. AT EACH POINT OF TIME, THE NETWORK DATA INTEGRITY AND CONSISTENCY CONDITIONS ARE FULFILLED.',
    'big_data': 'BIG DATA',
    'big_data_d': 'WE USE MODERN ALGORITHMS OF MACHINE LEARNING TO ENSURE THAT THE EMPLOYEES AS WELL AS THE COMPANIES OF THE SYSTEM ARE WELL-BALANCED BETWEEN EACH OTHER . EMPLOREUM IS FULLY ADAPTIVE TO CHANGES.',
    'sm_contracts': 'SMART CONTRACTS',
    'sm_contracts_d': 'SMART CONTRACTS ARE ACCOUNT HOLDING OBJECTS ON THE ETHEREUM BLOCKCHAIN. THEY CAN MAKE DECISIONS, STORE DATA, AND SEND ETHER TO OTHERS, WITHOUT ANY POSSIBILITY OF DOWNTIME, CENSORSHIP, FRAUD OR THIRD PARTY INTERFERENCE.',
    'w_tech': 'WEB TECHNOLOGIES',
    'w_tech_d': 'OUR EXPERIENCE IN COMBINING THE MOST ADVANCED WEB PROGRAMMING TOOLS AND TECHNOLOGIES ALLOWS US TO IMPLEMENT THE MOST CONVENIENT, UNDERSTANDABLE AND ADAPTIVE INTERFACE',
    'company': 'Company',
    'company_motivation': 'Be one of the first companies of the future',
    'dev': 'Developer',
    'dev_motivation': 'Are you a developer? Take the test to make our system better!',
    'pass_t': 'Pass the test',
    'submit': 'Submit'
  },
  'ru': {
    'intro': 'IT is the most developing sphere in the world. Therefore, the search for qualified employees requires great effort. We bring a new understanding of the labour market. Emploreum is a bridge between IT companies and specialists.Emploreum is a decentralized labor exchange where all contracts between employee and employer are made through Ethereum blockchain. A professional experience, education, current level of knowledge in certain areas of IT is a cv-token of the employees which are used to evaluate and rank them. Employees have a rating which is an indicator of the quality of their work. At the same time, companies also have a rating reflecting the level of the company. With the quality of maintenance of companies and employees, the System is able to determine the cost per hour of employee\'s work.',
    'about': 'О проекте',
    'team': 'team',
    'paper': 'paper',
    'technologies': 'technologies',
    'contact': 'contact',
    'short_descr': 'EDUCATION, EXPERIENCE, SKILLS - ONE TOKEN ON THE BLOCKCHAIN. THIS IS THE REVOLUTION IN RECRUITMENT OF IT EMPLOYEES.',
    'first_plus_n': 'A UNIQUE CV-TOKEN',
    'first_plus_d': 'Anyone can create his own labour book in the blockchain, which reflects the level of specific skills, experience, education, certificates.',
    'second_plus_n': 'ESCROW SMART CONTRACTS INSTEAD OF A LABOR CONTRACT',
    'second_plus_d': 'Jobs are a smart contract, with the requirement for work experience, and a level of certain skills.',
    'third_plus_n': 'Компания платит за скилы.',
    'third_plus_d': 'Каждый скил (JS, C ++) стоит денег на рынке труда. Компании выбирают уровень разработчика.',
    'four_plus_n': 'ВНУТРЕННЯЯ ВАЛЮТА',
    'four_plus_d': 'Время. Компании платят за каждый час работы сотрудника над заданием, используя определнные скилы или их комбинацию (JS ​​+ Ruby on Rails).',
    'tm': 'КОММАНДА',
    'rkh': 'Ринат Хатипов',
    'rkh_short': 'Основатель, front-end разработчик, дизайнер, CEO',
    'rkh_long': 'Студент университета иннополис. Solidity разработчик, front-end разработчик, разработчик мобильных приложений. Имеет опыт ведения IT компаний в городе Санкт-Петербург. Является сооснователем множества стартапов',
    'mik': 'Михаил Магомедов',
    'mik_short': 'Основатель, back-end разработчик, CEO',
    'mik_long': 'Студент Казанского Федерального университета. Имеет более 5 лет опыта разработки. Full stack веб разработчик. Участвовал в создании 3 стартапов',
    'ilg': 'Ильгиз Замалеев',
    'ilg_short': 'Founder, mobile-developer, UX, marketing',
    'ilg_long': 'Innopolis University student. ReactJS, React native, solidity developer. More than 3 years experience in web development.',
    'rig': 'Rinat Gumarov',
    'rig_short': 'Founder, back-end developer, big data',
    'rig_long': 'Innopolis University student. Solidity, Java, JavaScript developer. Have 3 years expirience in mobile development. Have expiriance in enterprice development.',
    'ay': 'Aydar Negimatzhanov',
    'ay_short': 'Founder, solidity developer, CEO',
    'ay_long': 'Innopolis University student. Solidity and Javascript developer. More than 1 year experience of developing Dapps using solidity. More than 5 blockchain projects.',
    'advisors': 'ADVISORS',
    'alg': 'Alexander Gryaznov',
    'alg_short': 'Chief Executive Officer',
    'alg_long': 'Cryptology Expert, programmer with more than 10 years experience. Alexander founded and conducts the first academic course on Ethereum at Innopolis University.',
    'w_paper': 'WHITE PAPER',
    'click_a_d': 'Click and Download',
    'paper_desc': 'this is what will help you understand',
    'tech_c': 'Technology cloud',
    'blockchain': 'BLOCK CHAIN',
    'blockchain_d': 'COMPLETELY DECENTRALIZED APPLICATION. IMMUTABLE RECORDS. YOUR CV-TOKEN CAN BE USED ANYWHERE. AT EACH POINT OF TIME, THE NETWORK DATA INTEGRITY AND CONSISTENCY CONDITIONS ARE FULFILLED.',
    'big_data': 'BIG DATA',
    'big_data_d': 'WE USE MODERN ALGORITHMS OF MACHINE LEARNING TO ENSURE THAT THE EMPLOYEES AS WELL AS THE COMPANIES OF THE SYSTEM ARE WELL-BALANCED BETWEEN EACH OTHER . EMPLOREUM IS FULLY ADAPTIVE TO CHANGES.',
    'sm_contracts': 'SMART CONTRACTS',
    'sm_contracts_d': 'SMART CONTRACTS ARE ACCOUNT HOLDING OBJECTS ON THE ETHEREUM BLOCKCHAIN. THEY CAN MAKE DECISIONS, STORE DATA, AND SEND ETHER TO OTHERS, WITHOUT ANY POSSIBILITY OF DOWNTIME, CENSORSHIP, FRAUD OR THIRD PARTY INTERFERENCE.',
    'w_tech': 'WEB TECHNOLOGIES',
    'w_tech_d': 'OUR EXPERIENCE IN COMBINING THE MOST ADVANCED WEB PROGRAMMING TOOLS AND TECHNOLOGIES ALLOWS US TO IMPLEMENT THE MOST CONVENIENT, UNDERSTANDABLE AND ADAPTIVE INTERFACE',
    'company': 'Company',
    'company_motivation': 'Be one of the first companies of the future',
    'dev': 'Developer',
    'dev_motivation': 'Are you a developer? Take the test to make our system better!',
    'pass_t': 'Pass the test',
    'submit': 'Submit'
  }
}

export default translations
